[TASK] Also allow newlines before the `?` operator
MyIntervals/emogrifier pull request #1089
Opened 2021-06-12 09:36 UTC by oliverklee

2021-06-12 20:41 UTC, JakeQZ requested changes
The wrong rule has been replaced - `LogicalOperatorSpacing` should be left unchanged (though I'm not sure what it does, it doesn't seem to be documented).

2021-06-12 20:41 UTC, JakeQZ commented on phpcs.xml
> -    <rule ref="Squiz.WhiteSpace.LogicalOperatorSpacing"/>
Looks like the wrong rule is replaced.

2021-06-12 20:41 UTC, JakeQZ commented on phpcs.xml
>      <rule ref="Squiz.WhiteSpace.OperatorSpacing"/>
It should be this one being replaced.

2021-06-13 09:01 UTC, oliverklee commented on phpcs.xml
>      <rule ref="Squiz.WhiteSpace.OperatorSpacing"/>
Good catch! Done.

2021-06-13 22:28 UTC, JakeQZ approved these changes

2021-06-13 22:28 UTC, merged