Disable HTML formatting by default
MyIntervals/emogrifier pull request #1214
Opened 2023-03-29 18:24 UTC by osbre

As discussed in https://github.com/MyIntervals/emogrifier/issues/1213

2023-03-30 13:35 UTC, oliverklee requested changes
Now that I think of it, this seems to really solve a problem/bug for you. I'd like to avoid this problem creeping back in. So would you be willing to add a small regression test (that fails without the change and passes with the change)?

2023-03-31 10:28 UTC, oliverklee approved these changes
Beautiful. Thanks for contributing this, @osbre! :heart:

2023-03-31 10:29 UTC, oliverklee commented
Oh, the PHP Sniffer is not happy. I'll fix this.

2023-03-31 11:40 UTC, oliverklee approved these changes

2023-03-31 11:40 UTC, merged

2023-04-04 00:01 UTC, JakeQZ reviewed
Sorry, I'm a bit late back to the party.

Good job both, particularly the thoughtful discussion about the rationale, motivation, whys and wherefores, etc.  I feel confident that the chosen solution is best.

However, I've spotted an issue with the `CHANGELOG` change which will need to be addressed.  I don't know if it's possible (or desirable) to make further changes in a PR which has already been approved and merged.

I've also added a couple of other comments which are somewhat neither here nor there, and nothing to worry about.

Thanks @osbre for contributing.

2023-04-04 16:15 UTC, osbre commented on CHANGELOG.md
> +
@JakeQZ Thanks, made a PR: https://github.com/MyIntervals/emogrifier/pull/1215

2023-04-04 16:51 UTC, osbre commented on tests/Unit/HtmlProcessor/AbstractHtmlProcessorTest.php
> +</html>';
Thanks, made the PR: https://github.com/MyIntervals/emogrifier/pull/1216