[FEATURE] Support preserving !important
MyIntervals/emogrifier pull request #1237
Opened 2023-09-21 22:47 UTC by penn5

2023-09-22 00:49 UTC, JakeQZ requested changes
Hi @penn5,

Thanks for contributing.  I think I can think of a situation where this would be useful: you retain the original CSS to cover the edge cases where Emogrifier does not quite (or cannot) work, but still want the inlined CSS to take precedence otherwise (and have some `!important` declarations in the original CSS).

The code changes look fine, but could you
- Add some unit tests to verify the behaviour is as expected;
- Update the README to document the new feature;
- Add an entry to the CHANGELOG?

Thanks <3

2023-09-22 00:55 UTC, JakeQZ requested changes
PS. I've enabled the running of the CI tests, which have picked up a couple of formatting issues.

2023-09-22 00:55 UTC, JakeQZ commented on src/CssInliner.php
> +     * @return self
I think the `phpdoc_separation` seperation error is coming from here, and needs a empty PHPDoc line between `@param` and `@return`.

2023-09-22 00:55 UTC, JakeQZ commented on src/CssInliner.php
> +    public function setRemoveImportantAnnotationFromAllInlineStyles(bool $removeImportantAnnotationFromAllInlineStyles): self
There's a line limit length of 120 characters.

2023-09-22 12:56 UTC, penn5 commented
I don't think I have time to learn whatever test framework you use, sorry.

2023-09-22 14:23 UTC, oliverklee commented
@penn5 If you want help/support for running and writing the tests, please let us know. We're willing to help.

2023-09-24 16:15 UTC, penn5 commented
Unfortunately I don't know anything about php unit testing and I don't really have time to learn. Sorry.

2023-09-24 17:24 UTC, oliverklee commented
Closing then. If at any time you would like to give a tests a go, please feel free to reopen this PR. We'll be happy to support you with the tests.

2023-09-24 17:24 UTC, closed without merging