[TASK] Upgrade Psalm to version 4.2
MyIntervals/emogrifier pull request #946
Opened 2020-11-22 17:33 UTC by oliverklee

Also regenerate the basline, but do not fix any code issues
(new or pre-existing).

Fixes #943

2020-11-22 17:38 UTC, JakeQZ approved these changes

2020-11-22 17:39 UTC, oliverklee commented
I don't get these Psalm failures locally … I'll need to have a look into this.

2020-11-22 17:40 UTC, JakeQZ requested changes
Looks OK, but it seems there are issues reported by the new Psalm version that need to be excepted in the baseline...

2020-11-23 18:46 UTC, oliverklee commented
I will switch the default git branch from `master` to `main` in a minute. GitHub then will autoclose all PRs targeted at the removed/renamed branch. Please create a new PR (from the existing PR branch) targeting `main`.

2020-11-23 18:49 UTC, closed without merging